//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightMixer.LightService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LightService.IDmxService")]
    public interface IDmxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmxService/SetDmxChannel", ReplyAction="http://tempuri.org/IDmxService/SetDmxChannelResponse")]
        void SetDmxChannel(int channel, byte value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmxService/UpdateAllDmxValue", ReplyAction="http://tempuri.org/IDmxService/UpdateAllDmxValueResponse")]
        void UpdateAllDmxValue(byte[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmxService/SetBreak", ReplyAction="http://tempuri.org/IDmxService/SetBreakResponse")]
        void SetBreak(long value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmxService/SetMBB", ReplyAction="http://tempuri.org/IDmxService/SetMBBResponse")]
        void SetMBB(long value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDmxService/SetMab", ReplyAction="http://tempuri.org/IDmxService/SetMabResponse")]
        void SetMab(long value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDmxServiceChannel : LightMixer.LightService.IDmxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DmxServiceClient : System.ServiceModel.ClientBase<LightMixer.LightService.IDmxService>, LightMixer.LightService.IDmxService {
        
        public DmxServiceClient() {
        }
        
        public DmxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DmxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetDmxChannel(int channel, byte value) {
            base.Channel.SetDmxChannel(channel, value);
        }
        
        public void UpdateAllDmxValue(byte[] value) {
            base.Channel.UpdateAllDmxValue(value);
        }
        
        public void SetBreak(long value) {
            base.Channel.SetBreak(value);
        }
        
        public void SetMBB(long value) {
            base.Channel.SetMBB(value);
        }
        
        public void SetMab(long value) {
            base.Channel.SetMab(value);
        }
    }
}
