//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualControler.Visual.Laser {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class LaserSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static LaserSetting defaultInstance = ((LaserSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LaserSetting())));
        
        public static LaserSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public short AS_Max_X_pos {
            get {
                return ((short)(this["AS_Max_X_pos"]));
            }
            set {
                this["AS_Max_X_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public short AS_Max_X_neg {
            get {
                return ((short)(this["AS_Max_X_neg"]));
            }
            set {
                this["AS_Max_X_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public short AS_Max_Y_neg {
            get {
                return ((short)(this["AS_Max_Y_neg"]));
            }
            set {
                this["AS_Max_Y_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public short AS_Max_Y_pos {
            get {
                return ((short)(this["AS_Max_Y_pos"]));
            }
            set {
                this["AS_Max_Y_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public short ASR_Max_X_pos {
            get {
                return ((short)(this["ASR_Max_X_pos"]));
            }
            set {
                this["ASR_Max_X_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public short ASR_Max_X_neg {
            get {
                return ((short)(this["ASR_Max_X_neg"]));
            }
            set {
                this["ASR_Max_X_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public short ASR_Max_y_pos {
            get {
                return ((short)(this["ASR_Max_y_pos"]));
            }
            set {
                this["ASR_Max_y_pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public short ASR_Max_y_neg {
            get {
                return ((short)(this["ASR_Max_y_neg"]));
            }
            set {
                this["ASR_Max_y_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int BS_Max_X {
            get {
                return ((int)(this["BS_Max_X"]));
            }
            set {
                this["BS_Max_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int SS_Max_X {
            get {
                return ((int)(this["SS_Max_X"]));
            }
            set {
                this["SS_Max_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int Te_Max_X {
            get {
                return ((int)(this["Te_Max_X"]));
            }
            set {
                this["Te_Max_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public short SE_Max_x_Pos {
            get {
                return ((short)(this["SE_Max_x_Pos"]));
            }
            set {
                this["SE_Max_x_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public short SE_Max_x_Neg {
            get {
                return ((short)(this["SE_Max_x_Neg"]));
            }
            set {
                this["SE_Max_x_Neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int SE_Max_y_Pos {
            get {
                return ((int)(this["SE_Max_y_Pos"]));
            }
            set {
                this["SE_Max_y_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public int SE_Max_y_neg {
            get {
                return ((int)(this["SE_Max_y_neg"]));
            }
            set {
                this["SE_Max_y_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int SER_Max_x_Pos {
            get {
                return ((int)(this["SER_Max_x_Pos"]));
            }
            set {
                this["SER_Max_x_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public int SER_Max_x_neg {
            get {
                return ((int)(this["SER_Max_x_neg"]));
            }
            set {
                this["SER_Max_x_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public short SER_Max_y_Pos {
            get {
                return ((short)(this["SER_Max_y_Pos"]));
            }
            set {
                this["SER_Max_y_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public short SER_Max_y_neg {
            get {
                return ((short)(this["SER_Max_y_neg"]));
            }
            set {
                this["SER_Max_y_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int SEF_Max_x_Pos {
            get {
                return ((int)(this["SEF_Max_x_Pos"]));
            }
            set {
                this["SEF_Max_x_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public int SEF_Max_x_neg {
            get {
                return ((int)(this["SEF_Max_x_neg"]));
            }
            set {
                this["SEF_Max_x_neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int SEF_Max_y_Pos {
            get {
                return ((int)(this["SEF_Max_y_Pos"]));
            }
            set {
                this["SEF_Max_y_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-25000")]
        public int SEF_Max_y_Neg {
            get {
                return ((int)(this["SEF_Max_y_Neg"]));
            }
            set {
                this["SEF_Max_y_Neg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int TE_Max_Y {
            get {
                return ((int)(this["TE_Max_Y"]));
            }
            set {
                this["TE_Max_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public short AS_SIZE {
            get {
                return ((short)(this["AS_SIZE"]));
            }
            set {
                this["AS_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int ASR_size {
            get {
                return ((int)(this["ASR_size"]));
            }
            set {
                this["ASR_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int Bs_Size {
            get {
                return ((int)(this["Bs_Size"]));
            }
            set {
                this["Bs_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int SS_Size {
            get {
                return ((int)(this["SS_Size"]));
            }
            set {
                this["SS_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int Te_SizeX {
            get {
                return ((int)(this["Te_SizeX"]));
            }
            set {
                this["Te_SizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public int TE_Size_Y {
            get {
                return ((int)(this["TE_Size_Y"]));
            }
            set {
                this["TE_Size_Y"] = value;
            }
        }
    }
}
