//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualControler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class dj : global::System.Configuration.ApplicationSettingsBase {
        
        private static dj defaultInstance = ((dj)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new dj())));
        
        public static dj Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Get or set the device number to play the wav out
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Get or set the device number to play the wav out")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MainOutDevice {
            get {
                return ((int)(this["MainOutDevice"]));
            }
            set {
                this["MainOutDevice"] = value;
            }
        }
        
        /// <summary>
        /// Monitor speak out
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Monitor speak out")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MonitorOutDevice {
            get {
                return ((int)(this["MonitorOutDevice"]));
            }
            set {
                this["MonitorOutDevice"] = value;
            }
        }
        
        /// <summary>
        /// Monitor Speaker Pair to use
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Monitor Speaker Pair to use")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MonitorSpeakerPair {
            get {
                return ((int)(this["MonitorSpeakerPair"]));
            }
            set {
                this["MonitorSpeakerPair"] = value;
            }
        }
        
        /// <summary>
        /// Main Speaker pair to use
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Main Speaker pair to use")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MainSpeakerPair {
            get {
                return ((int)(this["MainSpeakerPair"]));
            }
            set {
                this["MainSpeakerPair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoChangeEvent {
            get {
                return ((bool)(this["AutoChangeEvent"]));
            }
            set {
                this["AutoChangeEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TimeBetweenEvent {
            get {
                return ((int)(this["TimeBetweenEvent"]));
            }
            set {
                this["TimeBetweenEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentEvent {
            get {
                return ((int)(this["CurrentEvent"]));
            }
            set {
                this["CurrentEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int AutoMixDelay {
            get {
                return ((int)(this["AutoMixDelay"]));
            }
            set {
                this["AutoMixDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableExternalMixer {
            get {
                return ((bool)(this["EnableExternalMixer"]));
            }
            set {
                this["EnableExternalMixer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ExternalMixerDeviceNumber {
            get {
                return ((int)(this["ExternalMixerDeviceNumber"]));
            }
            set {
                this["ExternalMixerDeviceNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LaserDevice {
            get {
                return ((int)(this["LaserDevice"]));
            }
            set {
                this["LaserDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LaserSpeedAdj {
            get {
                return ((int)(this["LaserSpeedAdj"]));
            }
            set {
                this["LaserSpeedAdj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\cdcache\\")]
        public string CacheDirectory {
            get {
                return ((string)(this["CacheDirectory"]));
            }
            set {
                this["CacheDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16823")]
        public int PhidgetLEDSn {
            get {
                return ((int)(this["PhidgetLEDSn"]));
            }
            set {
                this["PhidgetLEDSn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68382")]
        public int PhidgetMixerSn {
            get {
                return ((int)(this["PhidgetMixerSn"]));
            }
            set {
                this["PhidgetMixerSn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44100")]
        public int BitRate {
            get {
                return ((int)(this["BitRate"]));
            }
            set {
                this["BitRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableLaser {
            get {
                return ((bool)(this["EnableLaser"]));
            }
            set {
                this["EnableLaser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemapeDriveFrom {
            get {
                return ((string)(this["RemapeDriveFrom"]));
            }
            set {
                this["RemapeDriveFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemapeDriveTo {
            get {
                return ((string)(this["RemapeDriveTo"]));
            }
            set {
                this["RemapeDriveTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManualBeatOnly {
            get {
                return ((bool)(this["ManualBeatOnly"]));
            }
            set {
                this["ManualBeatOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double LaserSpeedRatio {
            get {
                return ((double)(this["LaserSpeedRatio"]));
            }
            set {
                this["LaserSpeedRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoChangeEventLaser {
            get {
                return ((bool)(this["AutoChangeEventLaser"]));
            }
            set {
                this["AutoChangeEventLaser"] = value;
            }
        }
    }
}
